version: '2.1'
services:
    nginx:
        image: nginx:latest
        container_name: wpdev_nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
            - ./wordpress:/var/www/html
        links:
            - wordpress
            - mysql
        restart: always
    mysql:
        image: mariadb
        container_name: wpdev_mysql
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        healthcheck:
            test:  mysqladmin -uroot -ppassword ping || exit 1
            interval: 3s
            timeout: 1s
            retries: 5
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wpdev_phpmyadmin
        links:
            - mysql
        ports:
            - 8080:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: password
            PHP_UPLOAD_MAX_FILESIZE: 1G
            PHP_MAX_INPUT_VARS: 1G
        volumes:
            - /sessions
        depends_on:
            mysql:
                condition: service_healthy
        restart: always
    wordpress:
        image: wordpress:4.7.1-php7.0-fpm
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: wpdev_wordpress
        ports:
            - '9000:9000'
        volumes:
            - ./wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_PASSWORD=password
        links:
            - mysql
        depends_on:
            mysql:
                condition: service_healthy
        restart: always
