version: '2.1'
services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
            - ./wordpress:/var/www/html
        links:
            - wordpress
            - mysql
        restart: always
    mysql:
        image: mariadb
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: wp123
        healthcheck:
            test:  mysqladmin -uroot -pwp123 ping
            interval: 3s
            timeout: 1s
            retries: 5
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: wp123
            PHP_UPLOAD_MAX_FILESIZE: 1G
            PHP_MAX_INPUT_VARS: 1G
        volumes:
            - /sessions
        restart: always
    wordpress:
        image: wordpress:4.7.1-php7.0-fpm
        ports:
            - '9000:9000'
        volumes:
            - ./wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_PASSWORD=wp123
        links:
            - mysql
        depends_on:
            mysql:
                condition: service_healthy
        restart: always
    wpcli:
        image: wordpress:cli
        volumes:
            - ./wordpress:/var/www/html
        links:
            - mysql
        depends_on:
            mysql:
                condition: service_healthy
        healthcheck:
            test: curl --fail -s http://localhost:80/wp-admin/ || exit 1
        command: sh -c "sleep 20 && wp core install --path=/var/www/html --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=test@example.com"
